import { ObdDtcFault } from "../types/inspection";

export const OBD_DTC_DATABASE: ObdDtcFault[] = [
  {
    code: "P0016",
    system: "Powertrain",
    title: "Camshaft / Crankshaft Timing Correlation (Bank 1)",
    severity: "Fatal Deal-Breaker",
    points_deduction: -10,
    is_walk: true,
    estimated_repair_cost: 2400,
    symptoms: "Rough idle, lack of power, engine rattling on cold start.",
    explanation: "Mechanical synchronization mismatch between camshaft and crankshaft. Indicates stretched timing chain, broken chain guides, or failing VVT cam phasers. Imminent engine failure risk.",
    dealer_script: "WALK AWAY. Stretched timing chain or jumped cam gear requiring engine-out teardown ($2,400+). Do not purchase.",
  },
  {
    code: "P0420",
    system: "Emissions",
    title: "Catalytic Converter System Efficiency Below Threshold (Bank 1)",
    severity: "Severe",
    points_deduction: -5,
    is_walk: false,
    estimated_repair_cost: 1600,
    symptoms: "Check Engine Light illuminated, vehicle fails state emissions inspection.",
    explanation: "The downstream oxygen sensor detects that the catalytic converter substrate has degraded and can no longer clean exhaust gases. Requires OEM catalytic converter replacement.",
    dealer_script: "Catalytic converter failure detected (Code P0420). Vehicle will fail emissions test. Demand a $1,600 price deduction for OEM converter replacement.",
  },
  {
    code: "P0741",
    system: "Transmission",
    title: "Torque Converter Clutch Circuit Stuck OFF / Slipping",
    severity: "Fatal Deal-Breaker",
    points_deduction: -10,
    is_walk: true,
    estimated_repair_cost: 3500,
    symptoms: "Transmission slipping at highway speeds, high engine RPM, overheated ATF fluid.",
    explanation: "Internal hydraulic pressure loss or worn clutch lining in the torque converter lockup mechanism. Metal shavings typically contaminate the valve body.",
    dealer_script: "WALK AWAY. Transmission internal torque converter failure (Code P0741). Full transmission rebuild needed ($3,500–$4,500).",
  },
  {
    code: "P0300",
    system: "Powertrain",
    title: "Random / Multiple Cylinder Misfire",
    severity: "Severe",
    points_deduction: -5,
    is_walk: false,
    estimated_repair_cost: 850,
    symptoms: "Engine shaking, flashing Check Engine light under load, raw fuel odor.",
    explanation: "Combustion is failing intermittently across multiple cylinders. Common causes include failed ignition coils, worn spark plugs, intake vacuum leak, or low fuel pressure.",
    dealer_script: "Active multi-cylinder misfire detected (Code P0300). Deduct $850 for ignition coil replacement, spark plugs, and intake diagnosis.",
  },
  {
    code: "P0171",
    system: "Emissions",
    title: "System Too Lean (Bank 1)",
    severity: "Moderate",
    points_deduction: -3,
    is_walk: false,
    estimated_repair_cost: 450,
    symptoms: "Hesitation on acceleration, rough idle, poor fuel economy.",
    explanation: "ECU detected excessive unmetered air or inadequate fuel delivery. Commonly caused by a cracked intake boot, dirty Mass Airflow (MAF) sensor, or vacuum leak.",
    dealer_script: "Engine running lean on Bank 1 (Code P0171). Deduct $450 for smoke testing intake system, replacing intake gaskets, and cleaning MAF sensor.",
  },
  {
    code: "P0A80",
    system: "Electrical",
    title: "Replace Hybrid / EV High-Voltage Battery Pack",
    severity: "Fatal Deal-Breaker",
    points_deduction: -10,
    is_walk: true,
    estimated_repair_cost: 4200,
    symptoms: "Hybrid battery charge indicator dropping rapidly, engine running constantly, reduced acceleration.",
    explanation: "High-voltage battery module voltage divergence exceeds threshold. Internal nickel-metal hydride or lithium cells have permanently degraded.",
    dealer_script: "WALK AWAY. Main Hybrid High-Voltage Battery pack failure (Code P0A80). OEM battery replacement costs $4,200+.",
  },
  {
    code: "P0128",
    system: "Powertrain",
    title: "Coolant Thermostat Stuck Open (Below Regulating Temp)",
    severity: "Minor",
    points_deduction: -2,
    is_walk: false,
    estimated_repair_cost: 280,
    symptoms: "Engine takes a long time to warm up, lukewarm heater vent output in cold weather.",
    explanation: "Mechanical thermostat is stuck partially open, preventing engine from reaching optimal 190°F operating temperature.",
    dealer_script: "Thermostat stuck open (Code P0128). Deduct $280 for replacement thermostat, gasket, and coolant bleed.",
  },
  {
    code: "P0455",
    system: "Emissions",
    title: "EVAP System Gross Leak Detected",
    severity: "Minor",
    points_deduction: -1,
    is_walk: false,
    estimated_repair_cost: 95,
    symptoms: "Check Engine Light ON, fuel odor near gas cap.",
    explanation: "Evaporative emissions fuel vapor leak. Usually caused by a loose, cracked gas cap seal or sticking EVAP purge valve.",
    dealer_script: "EVAP fuel vapor leak detected (Code P0455). Request $95 for new OEM gas cap and purge test.",
  },
  {
    code: "B0001",
    system: "Safety",
    title: "Driver Airbag Deployment Loop Open / High Resistance",
    severity: "Fatal Deal-Breaker",
    points_deduction: -10,
    is_walk: true,
    estimated_repair_cost: 1200,
    symptoms: "SRS Airbag warning lamp permanently ON in gauge cluster.",
    explanation: "Electrical connection to steering wheel airbag clockspring is broken or prior airbag was deployed in an unrecorded accident. Airbag will NOT deploy in a crash.",
    dealer_script: "WALK AWAY. Airbag safety restraint failure (Code B0001). Extreme safety risk and evidence of prior collision damage.",
  }
];
