import { ComponentReferenceSet } from "../types/inspection";

export const VISUAL_KNOWLEDGE_BASE: Record<string, ComponentReferenceSet> = {
  s1_oil_cap: {
    itemId: "s1_oil_cap",
    component_name: "Oil Filler Cap Underside",
    bay_location_guide: "Located on the top-front of the engine valve cover. Twist counter-clockwise to remove and flip upside down.",
    what_to_look_for: "Inspect the inside seal and underside threads for yellow/white creamy mayonnaise emulsion (coolant intrusion) vs clean amber oil film.",
    references: [
      {
        type: "good",
        title: "Clean Amber Oil Film",
        visual_cue: "Golden or dark translucent oil film with zero froth or foam.",
        points: 2,
        sample_image_url: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      },
      {
        type: "concern",
        title: "Dark Baked Carbon Varnish",
        visual_cue: "Dry, dark brown or black crust baked on cap underside indicating extended oil change intervals.",
        points: -2,
        negotiation_script: "Request a $150 credit for an engine oil flush and fresh synthetic oil change.",
        sample_image_url: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      },
      {
        type: "critical",
        title: "Milky Mayonnaise Foam (Emulsion)",
        visual_cue: "Thick yellow, beige, or white frothy foam resembling milkshake or mayonnaise.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Catastrophic blown head gasket or cracked engine block. Do not negotiate.",
        sample_image_url: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop&q=80",
      },
    ],
  },
  s1_dipstick: {
    itemId: "s1_dipstick",
    component_name: "Engine Oil Dipstick",
    bay_location_guide: "Find the bright yellow or orange circular pull-ring handle on the front of the engine block.",
    what_to_look_for: "Pull out, wipe clean once, reinsert fully, and pull again. Check oil level between two indicator dots, viscosity, and lack of bubbles/froth.",
    references: [
      {
        type: "good",
        title: "Amber Full Level",
        visual_cue: "Oil sits exactly at upper full dot with clear golden/amber transparency.",
        points: 3,
        sample_image_url: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      },
      {
        type: "concern",
        title: "Jet Black / Overdue Service",
        visual_cue: "Oil is opaque pitch-black with heavy gasoline scent or sits below lower minimum dot.",
        points: -2,
        negotiation_script: "Ask for a $100 maintenance credit for an oil and filter change.",
        sample_image_url: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80",
      },
      {
        type: "critical",
        title: "Frothy Milkshake Slurry",
        visual_cue: "Milky, opaque caramel or light coffee slurry on dipstick blade.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Severe engine coolant breach into crankcase.",
        sample_image_url: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop&q=80",
      },
    ],
  },
  s1_coolant: {
    itemId: "s1_coolant",
    component_name: "Coolant Overflow Reservoir",
    bay_location_guide: "Look beside the radiator for the translucent plastic expansion tank with full/low markings.",
    what_to_look_for: "Inspect fluid color through the plastic tank. Look for floating black engine oil film or dark brown rust sediment.",
    references: [
      {
        type: "good",
        title: "Clean OEM Pink / Blue",
        visual_cue: "Transparent, vibrant OEM color (Toyota Pink/Blue) with zero floating particles.",
        points: 2,
      },
      {
        type: "concern",
        title: "Murky / Sediment Rust",
        visual_cue: "Cloudy liquid with dark sediment settled at bottom of reservoir.",
        points: -2,
        negotiation_script: "Request $200 off for a cooling system pressure test and flush.",
      },
      {
        type: "critical",
        title: "Oil Slick / Sludge Mix",
        visual_cue: "Black oil sheen floating on coolant or thick brown slurry inside tank.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Oil cooler rupture or blown head gasket breach.",
      },
    ],
  },
  s1_brake_fluid: {
    itemId: "s1_brake_fluid",
    component_name: "Brake Fluid Reservoir",
    bay_location_guide: "Located at the back of the engine bay on the driver side, mounted atop the brake booster.",
    what_to_look_for: "Check fluid darkness through translucent reservoir. Clear/honey = healthy. Dark brown/black = moisture degraded.",
    references: [
      {
        type: "good",
        title: "Clear Light Honey",
        visual_cue: "Transparent straw/honey color with zero moisture degradation.",
        points: 2,
      },
      {
        type: "concern",
        title: "Dark Brown / Pitch Black",
        visual_cue: "Dark iced-tea or dark brown color (>3% moisture content).",
        points: -2,
        negotiation_script: "Ask for a $150 credit for a hydraulic brake fluid flush.",
      },
    ],
  },
  s1_battery: {
    itemId: "s1_battery",
    component_name: "12V Battery Terminals & Date Code",
    bay_location_guide: "Mounted on the left or right side of engine bay with positive (+) red and negative (-) black terminals.",
    what_to_look_for: "Check for white/blue powder blooms on terminals and round circular date stamp (e.g. 05/23 = May 2023).",
    references: [
      {
        type: "good",
        title: "Clean Tight Posts (<3 yrs)",
        visual_cue: "Clean metal terminals with zero corrosion powder; battery under 3 years old.",
        points: 2,
      },
      {
        type: "concern",
        title: "Heavy Acid Crust (>5 yrs)",
        visual_cue: "Heavy blue/white sulfuric acid crust blooming around clamps; swollen casing.",
        points: -3,
        negotiation_script: "Deduct $220 for a new AGM battery replacement.",
      },
    ],
  },
  s2_timing_cover: {
    itemId: "s2_timing_cover",
    component_name: "Front Engine Timing Cover Seam",
    bay_location_guide: "Look down the passenger side of the engine along the aluminum mating seam between the cylinder head and engine block.",
    what_to_look_for: "Look for oil sweat, wet dark residue, or hanging oil drops along the aluminum seam where silicone sealant was applied.",
    references: [
      {
        type: "good",
        title: "Bone Dry Aluminum",
        visual_cue: "Dry, clean cast aluminum with zero dampness or road grime adhesion.",
        points: 3,
      },
      {
        type: "concern",
        title: "Active Wet Seepage / Grime Cake",
        visual_cue: "Wet black oil and grime accumulated along the timing cover perimeter seam.",
        points: -5,
        negotiation_script: "Require an $1,800 discount for front engine disassembly and timing cover reseal.",
      },
    ],
  },
  s2_valve_cover: {
    itemId: "s2_valve_cover",
    component_name: "Valve Cover Gasket Perimeter",
    bay_location_guide: "Top perimeter of the engine cylinder head directly above the exhaust manifolds.",
    what_to_look_for: "Look for wet oil pooling around the perimeter hold-down bolts or dripping onto the hot exhaust shield.",
    references: [
      {
        type: "good",
        title: "Dry Gasket Perimeter",
        visual_cue: "Clean, dry rubber seal without oil weeping.",
        points: 2,
      },
      {
        type: "concern",
        title: "Weeping / Oil Pooling",
        visual_cue: "Dark oil seepage coating the cylinder head ledge above exhaust manifold.",
        points: -4,
        negotiation_script: "Deduct $650 for valve cover reseal and spark plug tube seals.",
      },
    ],
  },
  s2_audio_idle: {
    itemId: "s2_audio_idle",
    component_name: "Cold Idle Acoustic Scan",
    bay_location_guide: "Hold phone microphone 12-18 inches above the center of the engine with hood open at 750 RPM idle.",
    what_to_look_for: "Listen for rhythmic percussive bottom-end double-knocks (rod knock) vs light ticking or smooth harmonic whirring.",
    references: [
      {
        type: "good",
        title: "Smooth Harmonic Idle",
        visual_cue: "Balanced combustion harmonics with zero deep metallic thuds.",
        points: 3,
      },
      {
        type: "concern",
        title: "High-Pitch Lifter Tick / Belt Chirp",
        visual_cue: "Rapid upper valvetrain ticking or accessory pulley squeal.",
        points: -2,
        negotiation_script: "Request $400 diagnostic and accessory pulley service credit.",
      },
      {
        type: "critical",
        title: "Heavy Metallic Rod Knock",
        visual_cue: "Deep, percussive hollow metallic hammer knock echoing from lower engine block.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Catastrophic engine bottom-end failure imminent. Teardown needed.",
      },
    ],
  },
  s2_audio_rev: {
    itemId: "s2_audio_rev",
    component_name: "Rev & Decel Acoustic Scan",
    bay_location_guide: "Record engine while an assistant blips throttle smoothly to 2,500 RPM and releases in Park.",
    what_to_look_for: "Listen for timing chain slap on deceleration or turbocharger high-pitch siren whistle.",
    references: [
      {
        type: "good",
        title: "Linear Spool & Quiet Return",
        visual_cue: "Smooth harmonic acceleration with clean, quiet return to base idle.",
        points: 2,
      },
      {
        type: "concern",
        title: "Timing Chain Decel Rattle",
        visual_cue: "Metallic chain rattle as RPM drops from 2,500 to 1,000 RPM (worn tensioner/guides).",
        points: -4,
        negotiation_script: "Deduct $1,200 for timing chain tensioner and guide replacement.",
      },
    ],
  },
  s2_serpentine_belt: {
    itemId: "s2_serpentine_belt",
    component_name: "Serpentine Accessory Drive Belt",
    bay_location_guide: "Located on the passenger side of the engine, looping around the alternator, water pump, and A/C compressor.",
    what_to_look_for: "Inspect the grooved underside for micro-cracks (>3 cracks per inch), dry rot, or frayed edges.",
    references: [
      {
        type: "good",
        title: "Supple Ribs, No Cracks",
        visual_cue: "Crisp black rubber grooves with zero transverse micro-cracking.",
        points: 2,
      },
      {
        type: "concern",
        title: "Dry Rot / Edge Fraying",
        visual_cue: "Multiple cracks across rubber ribs or frayed string along belt edge.",
        points: -3,
        negotiation_script: "Deduct $150 for serpentine belt replacement.",
      },
    ],
  },
  s3_cv_axle_boots: {
    itemId: "s3_cv_axle_boots",
    component_name: "Front CV Axle Rubber Boots",
    bay_location_guide: "Turn steering wheel fully to lock. Look behind the front brake rotor for the rubber accordion boots.",
    what_to_look_for: "Check for tears in the rubber folds and dark grease slung across the wheel well lining.",
    references: [
      {
        type: "good",
        title: "Intact, Sealed Rubber",
        visual_cue: "Accordion rubber boots are supple, securely clamped, with zero grease weeping.",
        points: 2,
      },
      {
        type: "concern",
        title: "Split Boot Slings Grease",
        visual_cue: "Tear in rubber accordion boot with dark green/black grease slung onto wheel well.",
        points: -3,
        negotiation_script: "Deduct $450 per side for front CV axle shaft replacement.",
      },
    ],
  },
  s3_oil_pan_leaks: {
    itemId: "s3_oil_pan_leaks",
    component_name: "Oil Pan & Bellhousing Joint",
    bay_location_guide: "Kneel under front bumper with flashlight. Look at lowest point of engine and transmission join.",
    what_to_look_for: "Look for hanging golden or black oil droplets at the inspection plate or drain bolt.",
    references: [
      {
        type: "good",
        title: "Clean Dry Metal",
        visual_cue: "Underside metal casing is bone dry with zero oil residue.",
        points: 3,
      },
      {
        type: "concern",
        title: "Hanging Drips (Rear Main Seal)",
        visual_cue: "Active wet oil droplets hanging from transmission bellhousing inspection port.",
        points: -5,
        negotiation_script: "Rear main seal requires transmission removal ($1,500). Demand full deduction.",
      },
    ],
  },
  s3_subframe_rust: {
    itemId: "s3_subframe_rust",
    component_name: "Subframe Cradle & Unibody Rails",
    bay_location_guide: "Inspect the steel front suspension cradle and unibody frame rail pinch welds behind the front wheels.",
    what_to_look_for: "Distinguish between superficial orange surface patina (safe) vs flaking delaminated metal or holes (unsafe).",
    references: [
      {
        type: "good",
        title: "Clean Factory Paint / Patina",
        visual_cue: "Factory e-coat with solid steel or minor cosmetic surface orange patina.",
        points: 3,
      },
      {
        type: "critical",
        title: "Perforated Rust / Flaking Rot",
        visual_cue: "Delaminating flaky rust layers or hole perforations in structural subframe.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Severe structural unibody rust failure. Vehicle is unsafe.",
      },
    ],
  },
  s3_struts_shocks: {
    itemId: "s3_struts_shocks",
    component_name: "Front Strut Dampers",
    bay_location_guide: "Look through the wheel opening at the chrome piston shaft inside the suspension spring.",
    what_to_look_for: "Check chrome piston shaft for mirror dryness vs wet hydraulic fluid running down the spring perch.",
    references: [
      {
        type: "good",
        title: "Dry Chrome Shaft",
        visual_cue: "Chrome hydraulic damper shaft is mirror dry and clean.",
        points: 2,
      },
      {
        type: "concern",
        title: "Wet Blown Strut",
        visual_cue: "Hydraulic damper oil leaking down strut body, attracting thick road grime.",
        points: -4,
        negotiation_script: "Deduct $850 for front strut pair replacement and 4-wheel alignment.",
      },
    ],
  },
  s4_panel_gaps: {
    itemId: "s4_panel_gaps",
    component_name: "Fender & Hood Panel Gaps",
    bay_location_guide: "Stand in front of vehicle and look down the gap lines between the hood and both front fenders.",
    what_to_look_for: "Check for uniform 3-4mm parallel gaps. Tapering, uneven gaps or rubbing panels indicate accident repair.",
    references: [
      {
        type: "good",
        title: "Uniform 3-4mm Gaps",
        visual_cue: "Consistent parallel gaps along entire hood perimeter on both left and right sides.",
        points: 2,
      },
      {
        type: "concern",
        title: "Crooked / Misaligned Seams",
        visual_cue: "Gap narrows to contact or widens past 7mm, indicating prior body repair.",
        points: -4,
        negotiation_script: "Demand a $2,000 accident repair discount or body shop alignment.",
      },
    ],
  },
  s4_inner_aprons_crash: {
    itemId: "s4_inner_aprons_crash",
    component_name: "Inner Fender Aprons & Core Support",
    bay_location_guide: "With hood open, inspect the painted sheet metal inner fender wells and upper radiator support beam.",
    what_to_look_for: "Look for neat circular factory spot welds and OEM sealer vs jagged manual MIG weld beads or crinkled metal.",
    references: [
      {
        type: "good",
        title: "Factory Spot Welds & Sealer",
        visual_cue: "Smooth factory stamped metal with round OEM spot welds and neat robotic seam sealer.",
        points: 3,
      },
      {
        type: "critical",
        title: "Kinked Metal / Manual Welds",
        visual_cue: "Crinkled sheet metal, clamp pull marks, or coarse manual weld beads from frame straightening.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Major structural front-end collision repair.",
      },
    ],
  },
  s4_paint_bondo: {
    itemId: "s4_paint_bondo",
    component_name: "Paint Texture & Body Filler / Bondo",
    bay_location_guide: "Sight down the doors and quarter panels at a 45-degree angle under daylight reflections.",
    what_to_look_for: "Look for waviness in reflections, tape lines in door jambs, or dull thick body filler patches.",
    references: [
      {
        type: "good",
        title: "Factory Orange Peel",
        visual_cue: "Consistent reflection and uniform clearcoat gloss across all panels.",
        points: 2,
      },
      {
        type: "concern",
        title: "Wavy Bondo / Overspray Lines",
        visual_cue: "Wavy reflections, paint overspray on rubber trim, or bubbling rust under filler.",
        points: -4,
        negotiation_script: "Deduct $800 for rust repair and panel refinishing.",
      },
    ],
  },
  s4_tire_tread: {
    itemId: "s4_tire_tread",
    component_name: "Tire Tread Depth & Wear Pattern",
    bay_location_guide: "Examine the contact patch of all 4 tires, checking outer edge, center, and inner shoulder.",
    what_to_look_for: "Check for even tread depth (>5/32\") vs bald inner/outer shoulders (alignment/camber fault) or sidewall bubbles.",
    references: [
      {
        type: "good",
        title: "Even 6/32\"+ Tread",
        visual_cue: "Uniform tread depth across entire tire surface with healthy sipes.",
        points: 2,
      },
      {
        type: "concern",
        title: "Bald Shoulder / Sidewall Bubble",
        visual_cue: "Inner shoulder worn bald down to steel belts or impact bubble on sidewall.",
        points: -4,
        negotiation_script: "Deduct $650 - $800 for replacement tires and 4-wheel alignment.",
      },
    ],
  },
  s5_tailpipe_smoke: {
    itemId: "s5_tailpipe_smoke",
    component_name: "Cold Start Tailpipe Smoke",
    bay_location_guide: "Stand behind the vehicle exhaust pipe 10 seconds after cold ignition startup.",
    what_to_look_for: "Clear or brief water vapor is normal. Blue smoke = oil burning. Billowing thick sweet white smoke = coolant burning.",
    references: [
      {
        type: "good",
        title: "Clear / Brief Vapor",
        visual_cue: "Clear exhaust or light transparent water vapor that dissipates within 3 feet.",
        points: 2,
      },
      {
        type: "critical",
        title: "Blue Oil Smoke Puff",
        visual_cue: "Bluish-grey smoke cloud with acrid oil scent indicating worn valve guide seals or piston rings.",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY. Severe internal engine oil consumption ($3,500+ engine teardown).",
      },
      {
        type: "critical",
        title: "Billowing Thick White Smoke",
        visual_cue: "Thick sweet-smelling white cloud that lingers in the air (coolant burning in cylinder).",
        points: -10,
        is_walk: true,
        negotiation_script: "WALK AWAY IMMEDIATELY. Blown head gasket or cracked cylinder head.",
      },
    ],
  },
  s5_warning_lights_obd: {
    itemId: "s5_warning_lights_obd",
    component_name: "Instrument Cluster Warning Lights",
    bay_location_guide: "Turn ignition ON (engine running) and photograph the main gauge cluster display.",
    what_to_look_for: "All indicator lamps (Check Engine, ABS, SRS Airbag, Oil Pressure) must self-test and completely extinguish.",
    references: [
      {
        type: "good",
        title: "Zero Fault Lamps",
        visual_cue: "All warning lamps illuminate during key-on self-test and extinguish within 3 seconds of engine running.",
        points: 3,
      },
      {
        type: "concern",
        title: "Check Engine / ABS Lamp ON",
        visual_cue: "Check Engine (MIL), ABS, or SRS Airbag amber/red lamp remains illuminated.",
        points: -5,
        negotiation_script: "Demand $800 - $1,500 deduction for OBD-II emission and safety diagnosis.",
      },
    ],
  },
  s5_trans_engagement: {
    itemId: "s5_trans_engagement",
    component_name: "Transmission Gear Engagement",
    bay_location_guide: "With foot firmly on brake at idle, shift from Park to Reverse, then to Drive.",
    what_to_look_for: "Check for smooth engagement in under 0.5s vs a 2-second lag followed by a violent mechanical thud.",
    references: [
      {
        type: "good",
        title: "Immediate Smooth Shift (<0.5s)",
        visual_cue: "Crisp, smooth hydraulic engagement into Reverse and Drive without harsh jolting.",
        points: 2,
      },
      {
        type: "concern",
        title: "Harsh Clunk / Slipping Lag",
        visual_cue: "2+ second engagement hesitation followed by harsh violent clunk into gear.",
        points: -5,
        negotiation_script: "Deduct $2,500 - $4,000 for transmission overhaul or walk away.",
      },
    ],
  },
  s5_hvac_performance: {
    itemId: "s5_hvac_performance",
    component_name: "HVAC System (A/C & Heat)",
    bay_location_guide: "Turn A/C to MAX cold with recirculation ON. Point infrared thermometer or feel center dash vent.",
    what_to_look_for: "Check for sub-45°F rapid cooling and scorching heater core output on full heat.",
    references: [
      {
        type: "good",
        title: "Sub-45°F A/C & Boiling Heat",
        visual_cue: "Air from center vent drops below 45°F in under 90 seconds; heater core blows strong hot air.",
        points: 2,
      },
      {
        type: "concern",
        title: "Hot Air Only / Dead Compressor",
        visual_cue: "A/C blows warm ambient air; compressor clutch does not engage.",
        points: -4,
        negotiation_script: "Deduct $900 for A/C compressor and condenser replacement.",
      },
    ],
  },
};
